### ISSUE TITLE
Error in rad clone

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#148]
```
java.lang.Throwable: There is no ProgressIndicator or Job in this thread, the current job is not cancellable.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJobInner(cancellation.kt:63)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJob(cancellation.kt:46)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:78)
	at com.intellij.openapi.vcs.checkout.PlatformProjectCheckoutListener.processCheckedOutDirectory(ProjectDirCheckoutListener.kt:40)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.checkoutCompleted(CompositeCheckoutListener.java:71)
	at network.radicle.jetbrains.radiclejetbrainsplugin.dialog.clone.CloneUtil.lambda$doClone$0(CloneUtil.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

**Comment by gsaslis** [comment]
let's include this in 0.3.0 if possible

**Comment by Stelios123** [comment]
Done. The fix is in feature/infoTab branch
