### ISSUE TITLE
"Memory leak detected"

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#149]
SEVERE - #c.i.o.u.ObjectTree - Memory leak detected: 'newDisposable' of class com.intellij.openapi.util.Disposer$1 is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

java.lang.RuntimeException: Memory leak detected: 'newDisposable' of class com.intellij.openapi.util.Disposer$1 is registered in Disposer but wasn't disposed.
Register it with a proper parentDisposable or ensure that it's always disposed by direct Disposer.dispose call.
See https://jetbrains.org/intellij/sdk/docs/basics/disposers.html for more details.
The corresponding Disposer.register() stacktrace is shown as the cause:

	at com.intellij.openapi.util.ObjectNode.assertNoChildren(ObjectNode.java:44)
	at com.intellij.openapi.util.ObjectTree.assertIsEmpty(ObjectTree.java:216)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:260)
	at com.intellij.openapi.util.Disposer.assertIsEmpty(Disposer.java:254)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeContainer(ApplicationImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:606)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:545)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:534)
	at com.intellij.openapi.application.ex.ApplicationEx.exit(ApplicationEx.java:70)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.quitApp(CloseProjectWindowHelper.kt:66)
	at com.intellij.openapi.wm.impl.CloseProjectWindowHelper.windowClosing(CloseProjectWindowHelper.kt:44)
	at com.intellij.openapi.wm.impl.ProjectFrameHelper$setupCloseAction$1.windowClosing(ProjectFrameHelper.kt:233)
	at java.desktop/java.awt.AWTEventMulticaster.windowClosing(AWTEventMulticaster.java:357)
	at java.desktop/java.awt.Window.processWindowEvent(Window.java:2107)
	at java.desktop/javax.swing.JFrame.processWindowEvent(JFrame.java:298)
	at java.desktop/java.awt.Window.processEvent(Window.java:2066)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5022)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2802)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4854)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:781)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:754)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:752)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:751)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:113)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:615)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:480)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.Throwable
	at com.intellij.openapi.util.ObjectNode.<init>(ObjectNode.java:25)
	at com.intellij.openapi.util.ObjectNode.findOrCreateChildNode(ObjectNode.java:141)
	at com.intellij.openapi.util.ObjectTree.register(ObjectTree.java:51)
	at com.intellij.openapi.util.Disposer.register(Disposer.java:143)
	at com.intellij.util.containers.DisposableWrapperList.createDisposableWrapper(DisposableWrapperList.java:254)
	at com.intellij.util.containers.DisposableWrapperList.add(DisposableWrapperList.java:63)
	at com.intellij.util.EventDispatcher.addListener(EventDispatcher.java:172)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addListener(ActionToolbarImpl.java:1468)
	at com.intellij.collaboration.ui.codereview.list.search.ReviewListSearchPanelFactory$QuickFilterButtonFactory.create(ReviewListSearchPanelFactory.kt:103)
	at com.intellij.collaboration.ui.codereview.list.search.ReviewListSearchPanelFactory.create(ReviewListSearchPanelFactory.kt:66)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.PatchListPanel.create(PatchListPanel.java:108)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.PatchTabController.viewPatches(PatchTabController.java:22)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.PatchTabController.<init>(PatchTabController.java:16)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.ToolWindow.createToolWindowContent(ToolWindow.java:22)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:543)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.getContentManager(ToolWindowImpl.kt:416)
	at com.intellij.openapi.vcs.changes.ui.VcsToolWindowFactory.init(VcsToolWindowFactory.kt:66)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1079)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows$registerToolWindows(ToolWindowSetInitializer.kt:134)
	at com.intellij.toolWindow.ToolWindowSetInitializer.createAndLayoutToolWindows(ToolWindowSetInitializer.kt:160)
	at com.intellij.toolWindow.ToolWindowSetInitializer.access$createAndLayoutToolWindows(ToolWindowSetInitializer.kt:46)
	at com.intellij.toolWindow.ToolWindowSetInitializer$initUi$3.invokeSuspend(ToolWindowSetInitializer.kt:106)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:194)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:813)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:429)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:74)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:114)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:36)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:779)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:730)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:749)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:909)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:756)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$5(IdeEventQueue.java:437)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:774)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:436)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:105)
	... 10 more
2022-12-13 17:31:08,649 [2160908] SEVERE - #c.i.o.u.ObjectTree - IntelliJ IDEA 2022.3  Build #IC-223.7571.182
2022-12-13 17:31:08,649 [2160908] SEVERE - #c.i.o.u.ObjectTree - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-12-13 17:31:08,649 [2160908] SEVERE - #c.i.o.u.ObjectTree - OS: Linux
2022-12-13 17:31:08,650 [2160909] SEVERE - #c.i.o.u.ObjectTree - Plugin to blame: Radicle version: 0.2.2
2022-12-13 17:31:08,652 [2160911]   INFO - #c.i.i.AppStarter - ------------------------------------------------------ IDE SHUTDOWN ------------------------------------------------------
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJobInner(cancellation.kt:63)
	at com.intellij.openapi.progress.CancellationKt.ensureCurrentJob(cancellation.kt:46)
	at com.intellij.openapi.progress.CoroutinesKt.runBlockingCancellable(coroutines.kt:78)
	at com.intellij.openapi.vcs.checkout.PlatformProjectCheckoutListener.processCheckedOutDirectory(ProjectDirCheckoutListener.kt:40)
	at com.intellij.openapi.vcs.checkout.CompositeCheckoutListener.checkoutCompleted(CompositeCheckoutListener.java:71)
	at network.radicle.jetbrains.radiclejetbrainsplugin.dialog.clone.CloneUtil.lambda$doClone$0(CloneUtil.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:246)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-12-13 17:01:05,687 [ 357946] SEVERE - #c.i.o.progress - IntelliJ IDEA 2022.3  Build #IC-223.7571.182
2022-12-13 17:01:05,687 [ 357946] SEVERE - #c.i.o.progress - JDK: 17.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2022-12-13 17:01:05,688 [ 357947] SEVERE - #c.i.o.progress - OS: Linux
2022-12-13 17:01:05,688 [ 357947] SEVERE - #c.i.o.progress - Plugin to blame: Radicle version: 0.2.2

**Comment by gsaslis** [comment]
let's include this in 0.3.0 if possible ;)

**Comment by gsaslis** [comment]
@JChrist could you assign the appropriate size label here please? (hours, days, months)?
