### ISSUE TITLE
Error when opening diff for new file in patch

### ISSUE THREAD

**Issue by JChrist** [cytechmobile/radicle-jetbrains-plugin#460]
Stacktrace is:

```
java.lang.NullPointerException: Cannot invoke "com.intellij.openapi.vfs.VirtualFile.getName()" because the return value of "com.intellij.openapi.vcs.changes.Change.getVirtualFile()" is null
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.review.ObservableThreadModel.getFileName(ObservableThreadModel.java:113)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.review.ObservableThreadModel.lambda$getInlineComments$2(ObservableThreadModel.java:76)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.review.ObservableThreadModel.getInlineComments(ObservableThreadModel.java:76)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.review.ObservableThreadModel.updateEditorCommentsUi(ObservableThreadModel.java:92)
	at network.radicle.jetbrains.radiclejetbrainsplugin.patches.review.ObservableThreadModel.lambda$update$0(ObservableThreadModel.java:43)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:249)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)

```

**Comment by Stelios123** [comment]
I tried this with a new file, and I didn't get the exception. I'm pretty sure that this bug has been fixed.
